google:
  url: http://203.36.98.91/search
  num: 25
  collection: active_collection
  client: active_frontend
  default_radius: 50
  filter: p
  output: xml_no_dtd
  getfields: *
cache:
  host: 10.248.98.129
  #host: 127.0.0.1
  timeout: 86400
flickr:
  url: http://api.flickr.com/services/rest
  key: 4998fab76787cf39383c563b32ce4b8f
  results: 6
youtube:
  url: http://gdata.youtube.com/feeds/api/videos
  results: 6