google:
  url: http://203.36.98.91/search
  num: 25
  collection: active_collection
  client: active_frontend
  default_radius: 50
  filter: p
  output: xml_no_dtd
  getfields: *
cache:
  timeout: 86400