insert into cities (name, state_id) values ('los angeles',5);
insert into cities (name, state_id) values ('chicago',14);
insert into cities (name, state_id) values ('houston',44);
insert into cities (name, state_id) values ('philadelphia',39);
insert into cities (name, state_id) values ('phoenix',3);
insert into cities (name, state_id) values ('san antonio',44);
insert into cities (name, state_id) values ('san diego',5);
insert into cities (name, state_id) values ('dallas',44);
insert into cities (name, state_id) values ('san jose',5);
insert into cities (name, state_id) values ('detroit',23);
insert into cities (name, state_id) values ('indianapolis',14);
insert into cities (name, state_id) values ('jacksonville',10);
insert into cities (name, state_id) values ('san francisco',5);
insert into cities (name, state_id) values ('columbus',36);
insert into cities (name, state_id) values ('austin',44);
insert into cities (name, state_id) values ('memphis',43);
insert into cities (name, state_id) values ('baltimore',21);
insert into cities (name, state_id) values ('fort worth',44);
insert into cities (name, state_id) values ('charlotte',34);
insert into cities (name, state_id) values ('el paso',44);
insert into cities (name, state_id) values ('milwaukee',50);
insert into cities (name, state_id) values ('seattle',48);
insert into cities (name, state_id) values ('boston',22);
insert into cities (name, state_id) values ('denver',6);
insert into cities (name, state_id) values ('washington dc',9);
insert into cities (name, state_id) values ('las vegas',29);
insert into cities (name, state_id) values ('portland',38);
insert into cities (name, state_id) values ('tucson',3);
insert into cities (name, state_id) values ('albuquerque',32);
insert into cities (name, state_id) values ('long beach',5);
insert into cities (name, state_id) values ('atlanta',11);
insert into cities (name, state_id) values ('fresno',5);
insert into cities (name, state_id) values ('sacramento',5);
insert into cities (name, state_id) values ('new orleans',19);
insert into cities (name, state_id) values ('cleveland',36);
insert into cities (name, state_id) values ('kansas city',26);
insert into cities (name, state_id) values ('mesa',3);
insert into cities (name, state_id) values ('virginia beach',47);
insert into cities (name, state_id) values ('omaha',28);
insert into cities (name, state_id) values ('oakland',5);
insert into cities (name, state_id) values ('miami',10);
insert into cities (name, state_id) values ('tulsa',37);
insert into cities (name, state_id) values ('honolulu',12);
insert into cities (name, state_id) values ('minneapolis',24);
insert into cities (name, state_id) values ('colorado springs',6);
insert into cities (name, state_id) values ('arlington',44);
insert into cities (name, state_id) values ('raleigh',34);